### ISSUE TITLE
MongoDB issue?

### ISSUE THREAD

**Issue by angela97lin** [ChristinaKo/Angela-Christina-mongo#1]
Hi guys!

Sometimes (for example, on the school CPU), I cannot run app.py because mongo refuses to connect... Here is the exact error message: 

(ENV)angela.lin@cslab1-17:~/Desktop/SoftDev_FoodMe$ python app.py &
[1] 25400
(ENV)angela.lin@cslab1-17:~/Desktop/SoftDev_FoodMe$ Traceback (most recent call last):
  File "app.py", line 3, in <module>
    import MongoWork
  File "/home/students/2015/angela.lin/Desktop/SoftDev_FoodMe/MongoWork.py", line 4, in <module>
    client = MongoClient()
  File "/home/students/2015/angela.lin/Desktop/ENV/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 369, in **init**
    raise ConnectionFailure(str(e))
pymongo.errors.ConnectionFailure: [Errno 111] Connection refused

I did some research and when I worked on this and had this error at home, I could just sudo service mongo restart or make sure that I had mongo running, but since I cannot use sudo on the school computer... Does anyone know how to solve this?

**Comment by angela97lin** [comment]
http://stackoverflow.com/questions/24599119/mongodb-not-working-error-dbpath-data-db-does-not-exist

This looks plausible, but I still cannot run the sudo command...

**Comment by angela97lin** [comment]
http://stackoverflow.com/questions/24269509/cannot-make-connection-with-pymongo

???
